### PR TITLE
Simplified code

### PR DESCRIPTION
**Pull request by natewatson999**
In this model, you can install a single script wiki-wide, and inject whatever feeds you want. I think this code is easier to maintain.

### CODE REVIEW

**Comment by VelvalineSnow** [comment]
1. This version compresses the code and as a result makes it harder to read. I don't support minifying it as it makes it **harder** to maintain as it is harder to read.
2. This version does the same as the last but in a different way. In the previous (current) version you can install the script site-wide and use the HTML to embed multiple widgets per page just the same as this.
3. You are injecting unsanitized attribute values into the page which can allow for script injection, something that cannot be looked past.

Overall I cannot say that I personally approve of this version and I think the current one is better.

Maybe @penguinstyles has a different opinion than I.

**Comment by natewatson999** [comment]
The difference is that this accommodates lists. Feel free to modify it to sanitize the fields. I never quite got the hang of that.

**Comment by VelvalineSnow** [comment]
I much prefer the current method of doing it (modifying the tag is a bit _eh..._) though that is simply my opinion. The current method allows for a bunch of containers to be added which I think keeps them nicely separated as opposed to a list.

As for sanitizing input you should use `mw.html.escape()`

Still not at all a fan of minimizing the code as I feel that at present it works the same and minifying it brings no real benefits other than premature obfuscation (which is done by load.php).

**Comment by natewatson999** [comment]
I was not aware of that function until just now. Thank you for telling me about it.

**Comment by VelvalineSnow** [comment]
Now the only issues are the minification and my question is _why_?

Why would we minify the code to several very long lines and change the input scheme from something simple and structured to a bunch of span tags with the exact same attributes as the embed code?

Even more odd, why embed the script when you can simply execute it in the same go?

**Comment by VelvalineSnow** [comment]
Unfortunately I still do not see why this version is preferable to the current one :red_circle:

**Comment by natewatson999** [comment]
Under this model, you can simply import this script once into MediaWiki:Common.js, and make feeds on any page. This is simpler because you only need to import once overall, not once per page. From what I understand, that's different from the current code.

**Comment by VelvalineSnow** [comment]
That is incorrect. The current version is meant to be placed in a JS page just the same. The only real difference (besides syntax) is that the current version is tailored to a template based system. Simply add multiple containers to a page and import the script and you will find out yourself.

**Comment by natewatson999** [comment]
So the main difference is that my version is span based and the other is mediawiki markup based? I think this is probably better, since it's more portable.

**Comment by VelvalineSnow** [comment]
1. Portability doesn't really matter because the script is purely for use on MediaWiki platforms.
2. It can be used just the same without MediaWiki markup but the current version makes it easier to turn into a template.

**Comment by VelvalineSnow** [comment]
I will leave this pending input from the other developer(s).

**Comment by natewatson999** [comment]
Also, this supports lists, whereas the previous version does not.

**Comment by VelvalineSnow** [comment]
The code does not need to support lists. To create a list with the current version just simply use multiple templates, it will process all templates and render the widgets.

The current version does everything this pull does and it does it in a way that adds the benefit of clean, structured code.

**Comment by penguinstyles** [comment]
I agree with @VelvalineSnow, I see no point in merging this PR when it does everything the existing code does.

**Comment by VelvalineSnow** [comment]
Alright then, closing as unconstructive.

**Comment by natewatson999** [comment]
There are people who embed Twitter lists on Wikia. I won't go against your decisions, so I'll just fork this.

**Pull request closed without merging**
